SSMCPushNotificationCenter/Models/tb_notification.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SSMCPushNotificationCenter.Models
{
    public class tb_notification
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please fill the title field")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please fill the message field")]
        public string Message { get; set; }
        
        public string Status { get; set; }

        [Required(ErrorMessage = "Please choose image first")]
        public byte[] Image { get; set; }
    }
}

SSMCPushNotificationCenter/Controllers/PushNotifController.cs
using Newtonsoft.Json;
using SSMCPushNotificationCenter.Models;
using SSMCPushNotificationCenter.Repositories;
using SSMCPushNotificationCenter.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SSMCPushNotificationCenter.Controllers
{
    public class PushNotifController : Controller
    {
        ApiService ap = new ApiService();
        HttpClient httpClient = new HttpClient();
        HttpResponseMessage response = new HttpResponseMessage();
        tb_notification myNotif = new tb_notification();

        public async Task<ActionResult> Index()
        {
            using (var client = new HttpClient())
            {
                response = httpClient.GetAsync(ap.GetData()).GetAwaiter().GetResult();

                if (response.IsSuccessStatusCode)
                {
                    string result = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                    myNotif = JsonConvert.DeserializeObject<tb_notification>(result);

                }

                return View(myNotif);
            }
        }  

        public async Task<ActionResult> Edit(int id)
        {
            tb_notification notif = null;

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(ap.Url());

                var responseTask = client.GetAsync(ap.GetDataById(id));
                responseTask.Wait();


                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<tb_notification>();
                    readTask.Wait();

                    notif = readTask.Result;
                }
            }
            
            return View(notif);
        }
        
        [HttpPost]
        public ActionResult Edit(tb_notification notif)
        {
            using (var client = new HttpClient())
            {
                if (ModelState.IsValid)
                {
                    client.BaseAddress = new Uri(ap.Url());

                    var putTask = client.PutAsJsonAsync<tb_notification>(ap.PutNotification(), notif);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {

                        return RedirectToAction("Index");
                    }
                }
            }
            return View(notif);
        }

        [HttpGet]
        public ActionResult Post()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Post(tb_notification notif)
        {
            using (var client = new HttpClient())
            {
                HttpPostedFileBase file = Request.Files["ImageData"];
                ContentRepository service = new ContentRepository();
                int i = service.UploadImageInDataBase(file, notif);

                if (i == 1)
                {
                    client.BaseAddress = new Uri(ap.Url());

                    var postTask = client.PostAsJsonAsync<tb_notification>(ap.PostNotification(), notif);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {

                        return RedirectToAction("Index");
                    }
                }

                else
                {
                    return View(notif);
                }
            }
            return View(notif);
        }
    }
}

SSMCPushNotificationCenter/Views/PushNotif/Edit.cshtml
@{
    /**/
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model SSMCPushNotificationCenter.Models.tb_notification

<div class="container" style="margin-top:20px">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken();


        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8">

                    <div class="form-group">
                        @Html.HiddenFor(model => model.Id)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Title)
                        @Html.TextBoxFor(m => m.Title, new { Id = "title", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Title, "", new { @style = "color:red" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Message)
                        @Html.TextAreaFor(m => m.Message, new { Id = "message", rows = "5", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Message, "", new { @style = "color:red" })
                    </div>
                    <div class="form-group">
                        <img class="img-responsive" src="img_chania.jpg" alt="Chania">
                        @Html.ValidationMessageFor(m => m.Image, "", new { @style = "color:red" })
                    </div>
                    <div class="form-horizontal">
                        <button type="submit" class="btn btn-primary" id="btnPush" value="Post" asp-controller="Post">Upload An Image</button>
                        <button type="submit" class="btn btn-primary" id="btnPush" value="Post" asp-controller="Post">Push Notification</button>
                    </div>
                    <div class="form-group">
                    </div>
                    <div class="form-group">
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        </div>
    }
</div>

SSMCPushNotificationCenter/Views/PushNotif/Index.cshtml
@{
    /**/

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model SSMCPushNotificationCenter.Models.tb_notification
 
<div class="container" style="margin-top:20px">
    <div class="form-group">
        <table class="table table-responsive">
            <tr>
                <th> Id </th>
                <th> Title </th>
                <th> Message </th>
                <th> Image </th>
                <th> Status </th>
                <th> Action </th>
            </tr>

            @if (Model != null)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Message)
                    </td>
                    <td>
                        <img class="img-responsive" src="cinqueterre.jpg" class="img-rounded" alt="Notification Images">
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Status)
                    </td>
                    <td>
                        @Html.ActionLink("Push", "Edit", new { id = Model.Id })
                    </td>
                </tr>
            }

            else
            {
                <tr>
                    <td> </td>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td> @Html.ActionLink("Push", "Post") </td>
                </tr>
            }

        </table>
    </div>
</div>

SSMCPushNotificationCenter/Views/PushNotif/Post.cshtml
@{
    ViewBag.Title = "Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model SSMCPushNotificationCenter.Models.tb_notification

<div class="container" style="margin-top:20px">

    @using (Html.BeginForm("Post", "PushNotif", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
                    @Html.AntiForgeryToken();


        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Title)
                        @Html.TextBoxFor(m => m.Title, new { Id = "title", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Title, "", new { @style = "color:red" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Message)
                        @Html.TextAreaFor(m => m.Message, new { Id = "message", rows = "5", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Message, "", new { @style = "color:red" })
                    </div>
                    @*<div class="form-group">
                        <img class="img-responsive" src="img_chania.jpg" alt="Notification Image">
                        @Html.ValidationMessageFor(m => m.Images, "", new { @style = "color:red" })
                    </div>*@
                    <div class="form-group">
                        @Html.LabelFor(model => model.Image)
                        <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);"                      
                        @Html.ValidationMessageFor(m => m.Image, "", new { @style = "color:red" })
                    </div>
                    <div class="form-group">
                         <button type="submit" class="btn btn-primary" id="btnPush" value="Post">Push Notification</button>
                    </div>
                    <div class="form-group">
                    </div>
                    <div class="form-group">
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    function fileCheck(obj) {
        var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
        if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only .jpeg, .jpg, .png, .gif, .bmp formats are allowed.");
        }
    }
</script>

SSMCPushNotificationCenter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Push Notification", "Index", "PushNotif", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "PushNotif")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>